# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36b827e1ba7238416cbada4ab278a4621976e1a1cd384c3ee2fbf19e2d1b25c60fc4fa916bd73c0553f0a00f7c66b9e838807b016507cc70b481252b3bb4da49

test:
  secret_key_base: d7c82a1357001f13056923537c40701e807d998ebb3a080ecb7c86c612d10cbd4158f3bd5bbd84abac795eec3b4da4c1121e99ae43ea8dfef354ca75b68df77c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
